In [1]:
import numpy as np


In [28]:
a = np.random.randint(0, 9, size=(10000, 10000))
print(a)

[[5 1 5 ... 3 4 4]
 [0 0 2 ... 3 0 3]
 [8 8 8 ... 5 7 3]
 ...
 [5 6 6 ... 6 4 8]
 [6 4 7 ... 3 7 0]
 [3 0 6 ... 0 6 3]]


In [29]:
a=a+1
print(a)

[[6 2 6 ... 4 5 5]
 [1 1 3 ... 4 1 4]
 [9 9 9 ... 6 8 4]
 ...
 [6 7 7 ... 7 5 9]
 [7 5 8 ... 4 8 1]
 [4 1 7 ... 1 7 4]]


In [30]:
a[::2] = 0
print(a)

[[0 0 0 ... 0 0 0]
 [1 1 3 ... 4 1 4]
 [0 0 0 ... 0 0 0]
 ...
 [6 7 7 ... 7 5 9]
 [0 0 0 ... 0 0 0]
 [4 1 7 ... 1 7 4]]


In [31]:
a[1::2, 1::2] = 0
print(a)

[[0 0 0 ... 0 0 0]
 [1 0 3 ... 0 1 0]
 [0 0 0 ... 0 0 0]
 ...
 [6 0 7 ... 0 5 0]
 [0 0 0 ... 0 0 0]
 [4 0 7 ... 0 7 0]]
